package main

import (
	"fmt"
	"os"
)


func main(){
	defer fmt.Println("!") //defer will not be runned when using os.Exit()

	os.Exit(3) //if 'go run os.Args[0]', return status will be picked by go
				// then "exit status 3"	will be printed
				// if run the program generated by "go build"
				// echo $? will print the return status code
}
